spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:~/order-service-db
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8080